"""Compatibility shim: job queue lives in images.jobs."""

from images.jobs import *  # noqa: F403
from images.jobs import (  # noqa: F401
    MCP_HANDOFF_DELAY_S,
    MCP_MAX_BATCH,
    MCP_POLL_WAIT_MAX_S,
    MCP_POLL_WAIT_S,
    JOBS_PERSIST_NAME,
    RESTART_ABANDON_REASON,
    CODING_ABANDON_REASON,
    McpImageItem,
    McpImageJob,
    _GENERATE_LOCK,
    _GENERATE_LOCK_LOOP,
    _MCP_JOBS,
    _MCP_JOB_ID,
    _MCP_ORDER,
    _MCP_TASK,
    _PERSIST_LOADED,
    _drop_dead_jobs,
    _new_items,
    _persist_jobs,
    _remember_mcp_job,
    _run_mcp_image_job,
    _signal,
    abandon_foreign_coding_job,
    abandon_inflight_jobs,
    active_mcp_image_job,
    ensure_comfy,
    generate_images_job,
    get_mcp_image_job,
    launch_mcp_image_job,
    loaded_tabby_name,
    note_coding_progress,
    mcp_job_to_dict,
    recent_mcp_image_jobs,
    refresh_job_wait,
    reload_last_llm,
    reset_mcp_image_jobs_for_tests,
    resume_persisted_jobs,
    start_mcp_image_job,
    wait_mcp_job_progress,
    wait_until_done,
)
