"""LLM intent + dest planner for mixed coding+images.

The loaded coding model decides whether this turn needs new PNGs, reuse of
files that already exist, or ordinary coding. Regex does not own that gate.
rewrite_comfy_prompt is only a safety net on the model's prompts.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import re
import uuid
from collections import OrderedDict
from dataclasses import dataclass, field
from pathlib import Path

from common.image_prompts import (
    MAX_PLANNED_IMAGES,
    resolved_image_size,
    rewrite_comfy_prompt,
)

LLM_PLAN_TIMEOUT_S = 25
VALID_ACTIONS = frozenset({"generate", "reuse", "none"})
MIXED_PLAN_SCHEMA = {
    "type": "object",
    "properties": {
        "action": {
            "type": "string",
            "enum": ["generate", "reuse", "none"],
        },
        "images": {
            "type": "array",
            "maxItems": 12,
            "items": {
                "type": "object",
                "properties": {
                    "filename": {"type": "string"},
                    "prompt": {"type": "string"},
                    "subject": {"type": "string"},
                    "size": {"type": "string"},
                },
            },
        },
    },
    "required": ["action", "images"],
}

CLASSIFY_SYSTEM = (
    "You organize image work for a local GPU. JSON only, no markdown. "
    "Read the whole conversation, especially This turn, the last assistant "
    "plan, and any files already in the project or generated in this chat.\n"
    "action:\n"
    "- generate: this turn (or the approved plan, if This turn is Implement "
    "the approved plan) explicitly asks to render NEW rasters now: generate/"
    "draw/render/recreate/replace a picture, qwen-image:, a new logo, a "
    "new hero photo, or ## Assets PNG/WebP dests that are not already in "
    "the project. Creating a landing page, website, or HTML page that should "
    "include a logo and/or a hero/header photo is generate for those dests "
    "when they are not already in the project. Putting NEW pictures onto an "
    "existing home page, panel, card, or section is generate for those dests "
    "even if they also ask for size, opacity, or blend. An existing logo or "
    "hero does not make this turn reuse when they asked for other new "
    "pictures (panels, cards, collection, generated by Comfy). Fill images with one "
    "object per new file. Do not infer generate from a CSS/layout follow-up "
    "that only mentions an existing logo or header. Mentions of pictures that "
    "already exist are reuse. Removing a border or "
    "frame on an attached picture is generate (img2img), not CSS.\n"
    "- reuse: files already exist (Already in the project / Already generated) "
    "and they only want them used in HTML/CSS. images must be []. Do not render.\n"
    "- none: ordinary coding, CSS/layout/overlay/opacity/z-index on pictures "
    "that already exist, an image "
    "that is not showing because of CSS, Build of a CSS-only plan whose "
    "Assets are None, questions, or "
    "a standalone generate-an-image line with no website/page. images must be [].\n"
    "images (generate only): filename is a basename like logo.png or mars.png, "
    "or a project path like pbptours/images/logo.png. prompt is the full Comfy "
    "prompt. Optional size is WIDTHxHEIGHT. Honor requested dimensions "
    "(1920x1080, 16:9, landscape, portrait). Banners/headers default to "
    "1536x768; portraits/9:16 to 768x1344. Logos, wordmarks, posters, "
    "buttons, and readable text start with qwen-image:. Hero/header/banner "
    "images are a scene, not a website screenshot. Keep the user's "
    "imaginary or fantasy description; do not substitute a stock real-world "
    "photograph unless they asked for one. One file per named subject they "
    "asked to create. If they also asked for video or audio on that page, "
    "include those dests too (videos/clip.mp4, audio/track.wav) with a short "
    "scene or music prompt. Do not invent a category. Skip CSS, HTML, "
    "JavaScript, React, Vue, pricing tiers, and etc."
)
SITE_IMAGE_ASK_RE = re.compile(
    r"(?is)\b(?:images?|pictures?|photos?|pics?|pngs?|logo|hero(?:\s+photo)?)\b"
)
SITE_VIDEO_ASK_RE = re.compile(
    r"(?is)\b(?:videos?|clips?|mp4|animations?)\b|\bwan:"
)
SITE_AUDIO_ASK_RE = re.compile(
    r"(?is)\b(?:audio|sfx|sound(?:\s*effects?)?)\b"
    r"|\b(?:add|include|with|need|want|generate|use)\b.{0,48}\b"
    r"(?:music|tracks?|songs?)\b"
)
SITE_MEDIA_TOOLS_RE = re.compile(
    r"(?is)\b(?:audio|video|image)s?(?:\s*/\s*|\s+and\s+|\s+)"
    r"(?:audio|video|image)s?\s+tools?\b"
    r"|\b(?:audio|video|image)\s+tools?\b"
    r"|\buse\s+(?:the\s+)?(?:gpu\s+)?(?:audio|video|image)"
)
_WIRE_EXISTING_MEDIA_RE = re.compile(
    r"(?is)\b(?:implement|wire|hook|drop)\b.{0,48}\b(?:into|onto|on|in)\b"
)
_MEDIA_SUFFIX = {
    ".png": "image",
    ".jpg": "image",
    ".jpeg": "image",
    ".webp": "image",
    ".gif": "image",
    ".mp4": "video",
    ".webm": "video",
    ".wav": "audio",
    ".flac": "audio",
    ".mp3": "audio",
}
_PLAN_CACHE: OrderedDict[str, "ImageTurnPlan"] = OrderedDict()
_PLAN_CACHE_MAX = 24
_SKIP_SLUGS = frozenset(
    {"etc", "css", "css3", "html", "html5", "js", "javascript", "react", "vue"}
)
_SLUG_RE = re.compile(r"[^a-z0-9]+")
_CSS_SLUG_RE = re.compile(
    r"(?is)^("
    r"[\d.-]+(?:px|em|rem|vh|vw|vmin|vmax|pct|deg|turn|fr|s|ms|ch|ex)?"
    r"|auto-fit|auto-fill|minmax|inherit|unset|initial|revert|none|auto"
    r"|linear-gradient|radial-gradient|repeat|rgba?|hsla?"
    r"|var-.+"
    r")$"
)
_SITE_FOLDER_RE = re.compile(
    r"(?is)\b(?:under|in|into|inside)\s+(?:the\s+)?"
    r"(?:folder|directory|dir)\s+[\"`'“”]?([A-Za-z][A-Za-z0-9._-]*)"
)


@dataclass
class ImageTurnPlan:
    action: str = "none"
    items: list[dict[str, str]] = field(default_factory=list)
    from_model: bool = False


def _spec_key(text: str) -> str:
    return hashlib.sha256((text or "").strip().encode()).hexdigest()


def remember_plan(text: str, plan: ImageTurnPlan) -> None:
    key = _spec_key(text)
    if key in _PLAN_CACHE:
        _PLAN_CACHE.move_to_end(key)
    _PLAN_CACHE[key] = ImageTurnPlan(
        action=plan.action,
        items=[dict(row) for row in plan.items],
        from_model=plan.from_model,
    )
    while len(_PLAN_CACHE) > _PLAN_CACHE_MAX:
        _PLAN_CACHE.popitem(last=False)


def recalled_plan(text: str) -> ImageTurnPlan | None:
    key = _spec_key(text)
    plan = _PLAN_CACHE.get(key)
    if not plan:
        return None
    _PLAN_CACHE.move_to_end(key)
    return ImageTurnPlan(
        action=plan.action,
        items=[dict(row) for row in plan.items],
        from_model=plan.from_model,
    )


def _content_text(content) -> str:
    if content is None:
        return ""
    if isinstance(content, str):
        return content
    parts = []
    for part in content:
        text = getattr(part, "text", None)
        if text:
            parts.append(text)
    return "\n".join(parts)


def classify_blob(data, prior_facts: str = "") -> str:
    """Conversation the classifier sees: history + this turn + known dests."""
    from common.phrase_switch import is_code_agent_nudge, last_user_text

    chunks: list[str] = []
    facts = (prior_facts or "").strip()
    if facts:
        if not facts.lower().startswith("already"):
            facts = f"Already generated in this chat:\n{facts}"
        chunks.append(facts)
    history: list[str] = []
    last_assistant = ""
    for message in getattr(data, "messages", None) or []:
        role = (getattr(message, "role", None) or "").lower()
        text = _content_text(getattr(message, "content", None)).strip()
        if not text:
            continue
        if role == "user":
            if is_code_agent_nudge(text):
                continue
            history.append(f"user: {text[:2000]}")
        elif role == "assistant":
            last_assistant = text
            if "tabby-image-job:" in text:
                history.append(f"assistant: {text[:500]}")
    if last_assistant and "tabby-image-job:" not in last_assistant:
        history.append(f"assistant: {last_assistant[:2000]}")
    if history:
        chunks.append("Conversation:\n" + "\n".join(history[-8:]))
    this_turn = (last_user_text(data) or "").strip()
    if this_turn:
        chunks.append(f"This turn:\n{this_turn[:2000]}")
    return "\n\n".join(chunks)[:6000]


def parse_plan_json(raw: str) -> list[dict[str, str]]:
    text = re.sub(r"(?is)<think>.*?</think>", " ", raw or "")
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.S)
    blob = fenced.group(1) if fenced else ""
    if not blob:
        start = text.find("{")
        end = text.rfind("}")
        if start >= 0 and end > start:
            blob = text[start : end + 1]
    if not blob:
        return []
    try:
        data = json.loads(blob)
    except json.JSONDecodeError:
        return []
    rows = data.get("images") if isinstance(data, dict) else data
    if not isinstance(rows, list):
        return []
    found: list[dict[str, str]] = []
    for row in rows:
        if not isinstance(row, dict):
            continue
        filename = str(row.get("filename") or row.get("output_path") or "").strip()
        subject = str(row.get("subject") or row.get("prompt") or "").strip()
        if filename or subject:
            row_out = {"filename": filename, "subject": subject}
            size = str(row.get("size") or "").strip()
            if size:
                row_out["size"] = size
            kind = str(row.get("modality") or "").strip().lower()
            if kind:
                row_out["modality"] = kind
            found.append(row_out)
    return found


def parse_turn_plan(raw: str) -> ImageTurnPlan | None:
    """Parse classifier JSON. None if there is no usable object."""
    text = re.sub(r"(?is)<think>.*?</think>", " ", raw or "")
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.S)
    blob = fenced.group(1) if fenced else ""
    if not blob:
        start = text.find("{")
        end = text.rfind("}")
        if start >= 0 and end > start:
            blob = text[start : end + 1]
    if not blob:
        return None
    try:
        data = json.loads(blob)
    except json.JSONDecodeError:
        return None
    if not isinstance(data, dict):
        return None
    action = str(data.get("action") or "").strip().lower()
    rows = parse_plan_json(raw)
    if action not in VALID_ACTIONS:
        action = "generate" if rows else "none"
    if action != "generate":
        return ImageTurnPlan(action=action, items=[], from_model=True)
    return ImageTurnPlan(action="generate", items=[], from_model=True)


def _subject_slug(name: str) -> str:
    slug = _SLUG_RE.sub("-", (name or "").strip().lower()).strip("-")
    return slug[:40]


def site_images_dir(text: str) -> str:
    match = _SITE_FOLDER_RE.search(text or "")
    folder = (match.group(1) if match else "").strip().strip("/")
    if folder and folder.lower() not in {"images", "image", "v1", "openai"}:
        return f"{folder}/images"
    return "images"


def item_modality(row) -> str:
    if isinstance(row, dict):
        kind = str(row.get("modality") or "").strip().lower()
        path = str(row.get("output_path") or row.get("filename") or "")
    else:
        kind = str(getattr(row, "modality", "") or "").strip().lower()
        path = str(getattr(row, "output_path", "") or "")
    if kind in ("audio", "music", "video", "i2v", "image"):
        return kind
    return _MEDIA_SUFFIX.get(Path(path).suffix.lower(), "image")


def site_asks_for_images(text: str) -> bool:
    return bool(SITE_IMAGE_ASK_RE.search(text or ""))


def site_asks_for_video(text: str) -> bool:
    raw = text or ""
    return bool(SITE_VIDEO_ASK_RE.search(raw) or SITE_MEDIA_TOOLS_RE.search(raw))


def site_asks_for_audio(text: str) -> bool:
    raw = text or ""
    return bool(SITE_AUDIO_ASK_RE.search(raw) or SITE_MEDIA_TOOLS_RE.search(raw))


def site_wants_generated_media(text: str) -> bool:
    """True when this turn asked the GPU for page images, audio, or video."""
    raw = text or ""
    if SITE_MEDIA_TOOLS_RE.search(raw):
        return True
    from common.phrase_switch import is_coding_task

    if _WIRE_EXISTING_MEDIA_RE.search(raw) and not (
        site_asks_for_video(raw) or site_asks_for_audio(raw)
    ):
        return False
    if not is_coding_task(raw):
        return bool(site_asks_for_video(raw) or site_asks_for_audio(raw))
    return bool(
        site_asks_for_images(raw)
        or site_asks_for_video(raw)
        or site_asks_for_audio(raw)
    )


def _site_theme(text: str) -> str:
    from common.image_prompts import company_name

    brand = company_name(text or "")
    if brand:
        return brand
    raw = re.sub(r"(?is)\b(?:create|write|make|build|add|include)\b", " ", text or "")
    raw = re.sub(r"(?is)\b(?:website|web\s*page|webpage|landing\s*page)\b", " ", raw)
    raw = re.sub(r"(?is)\b(?:video|audio|images?|where possible)\b", " ", raw)
    cleaned = re.sub(r"\s+", " ", raw).strip(" .,")
    return cleaned[:80] or "the scene the user described"


def plan_from_extracted(text: str, rows: list[dict[str, str]]) -> list[dict[str, str]]:
    dest_dir = site_images_dir(text)
    items: list[dict[str, str]] = []
    seen: set[str] = set()
    for row in rows or []:
        if len(items) >= MAX_PLANNED_IMAGES:
            break
        raw_path = str(row.get("filename") or row.get("output_path") or "")
        raw_path = raw_path.replace("\\", "/").lstrip("/")
        filename = raw_path.split("/")[-1].strip()
        slug = _subject_slug(filename.rsplit(".", 1)[0] if filename else "")
        if not slug:
            slug = _subject_slug(str(row.get("subject") or ""))
        if (
            not slug
            or slug in seen
            or slug in _SKIP_SLUGS
            or _CSS_SLUG_RE.match(slug)
        ):
            continue
        subject = str(row.get("subject") or slug).strip() or slug
        modality = item_modality(row if isinstance(row, dict) else {"filename": filename})
        if not str(row.get("modality") or "").strip():
            modality = _MEDIA_SUFFIX.get(Path(filename or raw_path).suffix.lower(), "image")
        seen.add(slug)
        if modality in ("video", "i2v"):
            name = filename if Path(filename).suffix.lower() in {".mp4", ".webm"} else f"{slug}.mp4"
            dest = raw_path if "/" in raw_path and Path(raw_path).suffix.lower() in {".mp4", ".webm"} else f"videos/{name}"
            items.append(
                {
                    "prompt": subject,
                    "output_path": dest,
                    "size": str(row.get("size") or "640x640"),
                    "modality": "video" if modality != "i2v" else "i2v",
                }
            )
            continue
        if modality in ("audio", "music"):
            name = filename if Path(filename).suffix.lower() in {".wav", ".flac", ".mp3"} else f"{slug}.wav"
            dest = raw_path if "/" in raw_path and Path(raw_path).suffix.lower() in {".wav", ".flac", ".mp3"} else f"audio/{name}"
            items.append(
                {
                    "prompt": subject,
                    "output_path": dest,
                    "size": str(row.get("size") or "1024x1024"),
                    "modality": "music" if modality == "music" else "audio",
                }
            )
            continue
        name = "logo.png" if slug == "logo" else f"{slug}.png"
        if slug == "header" or slug == "banner":
            name = "header.png"
        if "/" in raw_path and Path(raw_path).suffix.lower() in {
            ".png",
            ".jpg",
            ".jpeg",
            ".webp",
            ".gif",
        }:
            dest = raw_path
            if Path(dest).suffix.lower() != ".png":
                dest = str(Path(dest).with_suffix(".png"))
        else:
            dest = f"{dest_dir}/{name}".replace("//", "/")
        items.append(
            {
                "prompt": rewrite_comfy_prompt(subject),
                "output_path": dest,
                "size": resolved_image_size(
                    prompt=subject,
                    filename=filename or name,
                    size=row.get("size"),
                    spec=text,
                ),
                "modality": "image",
            }
        )
    return items


def plan_mixed_site_media(
    text: str, existing: list[dict[str, str]] | None = None
) -> list[dict[str, str]]:
    """PNG dests plus video/audio when a Code page ask named those media."""
    from common.image_prompts import SCENE_TAIL, plan_mixed_images

    raw = text or ""
    items = [dict(row) for row in (existing or [])]
    if not items and site_asks_for_images(raw):
        items = [dict(row) for row in plan_mixed_images(raw)]
        for row in items:
            row.setdefault("modality", "image")
    if site_asks_for_images(raw) and not any(item_modality(row) == "image" for row in items):
        theme = _site_theme(raw)
        items.append(
            {
                "prompt": rewrite_comfy_prompt(
                    f"wide photographic scene of {theme}, atmospheric, {SCENE_TAIL}"
                ),
                "output_path": "images/hero.png",
                "size": "1536x768",
                "modality": "image",
            }
        )
        if re.search(r"(?is)\b(?:music|album|record|vinyl|store)\b", raw):
            items.append(
                {
                    "prompt": rewrite_comfy_prompt(
                        "qwen-image: A music album cover with abstract neon waves "
                        "and a stylized microphone, 768x768"
                    ),
                    "output_path": "images/album.png",
                    "size": "768x768",
                    "modality": "image",
                }
            )
    if site_asks_for_video(raw) and not any(item_modality(row) in ("video", "i2v") for row in items):
        theme = _site_theme(raw)
        items.append(
            {
                "prompt": f"a short cinematic clip of {theme}, gentle camera motion",
                "output_path": "videos/clip.mp4",
                "size": "640x640",
                "modality": "video",
            }
        )
    if site_asks_for_audio(raw) and not any(item_modality(row) in ("audio", "music") for row in items):
        music = bool(re.search(r"(?is)\b(?:music|song|track|album|playlist|store)\b", raw))
        theme = _site_theme(raw)
        items.append(
            {
                "prompt": (
                    "warm vinyl store playlist, lo-fi beat with soft keys, no vocals"
                    if music
                    else f"ambient sound of {theme}"
                ),
                "output_path": "audio/track.wav",
                "size": "1024x1024",
                "modality": "music" if music else "audio",
            }
        )
    return items[:MAX_PLANNED_IMAGES]


def fallback_item(text: str = "") -> list[dict[str, str]]:
    """Unused by the live gate. Kept for older unit tests."""
    dest_dir = site_images_dir(text)
    return [
        {
            "prompt": rewrite_comfy_prompt("wide photographic scene"),
            "output_path": f"{dest_dir}/generated.png",
        }
    ]


def _plan_from_model_text(spec: str, raw: str) -> ImageTurnPlan | None:
    parsed = parse_turn_plan(raw)
    if parsed is None:
        rows = parse_plan_json(raw)
        if not rows:
            return None
        parsed = ImageTurnPlan(action="generate", items=[], from_model=True)
        items = plan_from_extracted(spec, rows)
        return ImageTurnPlan(
            action="generate" if items else "none",
            items=items,
            from_model=True,
        )
    if parsed.action != "generate":
        return parsed
    items = plan_from_extracted(spec, parse_plan_json(raw))
    if not items:
        return ImageTurnPlan(action="none", items=[], from_model=True)
    return ImageTurnPlan(action="generate", items=items, from_model=True)


async def _llm_json_via_backend(system: str, user: str) -> str:
    try:
        from sidecar.settings import is_sidecar_process

        if not is_sidecar_process():
            return ""
        from sidecar.proxy import generate_chat
        from endpoints.OAI.types.chat_completion import (
            ChatCompletionMessage,
            ChatCompletionRequest,
        )
    except Exception:
        return ""
    request = ChatCompletionRequest(
        messages=[
            ChatCompletionMessage(role="system", content=system),
            ChatCompletionMessage(role="user", content=(user or "")[:6000]),
        ],
        max_tokens=800,
        temperature=0.1,
        json_schema=MIXED_PLAN_SCHEMA,
        stream=False,
    )
    try:
        raw = await asyncio.wait_for(
            generate_chat(request.model_dump(mode="json", exclude_none=True)),
            timeout=LLM_PLAN_TIMEOUT_S,
        )
    except Exception as exc:
        from common.logger import xlogger

        xlogger.warning(f"Mixed image classify via backend failed: {exc}")
        return ""
    choices = raw.get("choices") if isinstance(raw, dict) else None
    if not isinstance(choices, list) or not choices:
        return ""
    message = choices[0].get("message") if isinstance(choices[0], dict) else None
    if not isinstance(message, dict):
        return ""
    return str(message.get("content") or message.get("text") or "")


async def _llm_json(system: str, user: str, disconnect_handler=None) -> str:
    try:
        from common import model as model_mod
        from endpoints.OAI.types.chat_completion import (
            ChatCompletionMessage,
            ChatCompletionRequest,
        )
        from endpoints.OAI.utils.chat_completion import apply_chat_template
    except Exception:
        return ""
    container = getattr(model_mod, "container", None)
    if not container or not getattr(container, "loaded", False):
        return await _llm_json_via_backend(system, user)
    if getattr(container, "prompt_template", None) is None:
        return ""
    request = ChatCompletionRequest(
        messages=[
            ChatCompletionMessage(role="system", content=system),
            ChatCompletionMessage(role="user", content=(user or "")[:6000]),
        ],
        max_tokens=800,
        temperature=0.1,
        json_schema=MIXED_PLAN_SCHEMA,
    )
    try:
        prompt, embeddings = await apply_chat_template(request)
        result = await asyncio.wait_for(
            container.generate(
                f"mixed-plan-{uuid.uuid4().hex[:12]}",
                prompt,
                request,
                mm_embeddings=embeddings,
                disconnect_handler=disconnect_handler,
            ),
            timeout=LLM_PLAN_TIMEOUT_S,
        )
    except Exception as exc:
        from common.logger import xlogger

        xlogger.warning(f"Mixed image classify failed: {exc}")
        return ""
    if isinstance(result, dict):
        return str(result.get("text") or result.get("content") or "")
    return ""


async def llm_classify_turn(
    data,
    disconnect_handler=None,
    prior_facts: str = "",
) -> ImageTurnPlan:
    """Ask the loaded coding model what this turn needs. none if it cannot run."""
    from common.phrase_switch import last_user_text

    blob = classify_blob(data, prior_facts=prior_facts)
    if not blob.strip():
        return ImageTurnPlan()
    raw = await _llm_json(CLASSIFY_SYSTEM, blob, disconnect_handler=disconnect_handler)
    if not raw.strip():
        return ImageTurnPlan()
    spec = (last_user_text(data) or blob).strip()
    plan = _plan_from_model_text(spec, raw)
    if plan is None:
        plan = ImageTurnPlan()
    from common.gen_logging import log_image_translator

    log_image_translator(
        plan.action,
        plan.items,
        source="classify",
        user_text=spec,
    )
    return plan


async def classify_image_turn(
    data,
    disconnect_handler=None,
    prior_facts: str = "",
) -> ImageTurnPlan:
    """Cached classify for this conversation blob."""
    key = classify_blob(data, prior_facts=prior_facts)
    remembered = recalled_plan(key)
    if remembered is not None:
        from common.gen_logging import log_image_translator
        from common.phrase_switch import last_user_text

        log_image_translator(
            remembered.action,
            remembered.items,
            source="classify cache",
            user_text=last_user_text(data) or "",
        )
        return remembered
    plan = await llm_classify_turn(
        data, disconnect_handler=disconnect_handler, prior_facts=prior_facts
    )
    if plan.from_model:
        remember_plan(key, plan)
    return plan


async def llm_plan_images(text: str, disconnect_handler=None) -> list[dict[str, str]]:
    """Ask the loaded coding model for dests. Empty if it cannot run."""
    from endpoints.OAI.types.chat_completion import (
        ChatCompletionMessage,
        ChatCompletionRequest,
    )

    raw = (text or "").strip()
    if not raw:
        return []
    data = ChatCompletionRequest(
        messages=[ChatCompletionMessage(role="user", content=raw)]
    )
    plan = await llm_classify_turn(data, disconnect_handler=disconnect_handler)
    return list(plan.items) if plan.action == "generate" else []


async def plan_mixed_dests(text: str, disconnect_handler=None) -> list[dict[str, str]]:
    """Dests when the model chooses generate. Empty means do not render."""
    from endpoints.OAI.types.chat_completion import (
        ChatCompletionMessage,
        ChatCompletionRequest,
    )

    raw = text or ""
    data = ChatCompletionRequest(
        messages=[ChatCompletionMessage(role="user", content=raw)]
    )
    plan = await classify_image_turn(data, disconnect_handler=disconnect_handler)
    if plan.action == "generate":
        return list(plan.items)
    return []
